server:
  port: 9002
  trustedPathPrefix: /external/
  trustedPort: 9003


# 单数据源配置
spring:
  application:
    name: spring-boot-jpa-hikari
  datasource:
    url: jdbc:mysql://localhost:3306/bbs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ENC(2f4nGo/79Lf+QA28d3KWoA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource
  #jpa 配置
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  #mail配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: jogfwxnofmwgjaah
    port: 25
    username: 1797262364@qq.com
#jasypt加密
jasypt:
  encryptor:
    password: king991214